site_name: arxiv_2024_nlp_contributions
nav:
  - Home: index.md

theme:
  name: material

plugins:
  - search
  - mkdocstrings:
      project_name: arxiv_2024_nlp_contributions
      handlers:
        python:
          options:
            docstring_style: numpy